### ISSUE TITLE
It doesn't work properly

### ISSUE THREAD

**Issue by emirtuncer** [justanotherdevel/whatsapp-tracking#1]
i don't know why but it just shows start time like:

Thu Dec 20 2018 23:41:06 GMT+0300 (GMT+03:00)

and doesn't log online and typing status. i thought it was because of language and i changed it english it worked like 5 min and broke again when i closed window.

**Comment by rizwansoaib** [comment]
https://github.com/rizwansoaib/whatsapp-monitor
